spring:
  mail:
    protocol: smtp
    host: smtp.163.com
    username: 15827753867@163.com
    password: IJMVJXLGXCJNPWBQ
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: NACO2koio
      expire: 7
  datasource:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jwtandredisproject
springdoc:
  api-docs:
    path: /api-docs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl